# -*- coding: utf-8 -*-
"""Fajar Febryan.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1B_5IOZb_WM-P_NALJqjXyP9XZKeCvFBV
"""

import numpy as np
import pandas as pd

dataset = pd.read_csv ("Dataset_Transaksi.csv")
x=dataset.iloc[:,[2,3]].values
y=dataset.iloc[:,-1].values

print(x)

print(y)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.25,random_state=0)

print(x_train)

print(x_test)



print(y_train)

print(y_test)

from pandas.core.common import standardize_mapping
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

print(x_test)

from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(x_train,y_train)

y_pred = classifier.predict(x_test)

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred)

print(cm)

var1=8
var2=5
var3=2
var4=10
hasil = (var1+var2)/(var1+var2+var3+var4)*100

print(hasil)